leader:
  robot_type: franka
  publish_frequency: 100.0
  time_to_home: 5.0
  home_config: [2.049553, -0.693968, -1.447995, -1.647495, -0.073369, 2.056294, 0.551513]
use_gripper: false
leader_gripper:
  min_value: 0.0
  max_value: 1.0
leader_namespace: leader
gravity_compensation_controller: control/fr3_leader_freedrive.yaml
