leader:
  robot_type: franka
  publish_frequency: 100.0
  time_to_home: 5.0
  home_config: [1.464304, -1.286791, -1.145468, -2.031606, -0.586394, 1.930747, -0.000461]
use_gripper: false
leader_gripper:
  min_value: 0.0
  max_value: 1.0
leader_namespace: leader
gravity_compensation_controller: control/fr3_leader_freedrive.yaml
